# Generated by Django 5.2.13 on 2026-04-22 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('reporting_id', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('address_line1', models.CharField(max_length=300)),
                ('address_line2', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(choices=[('India', 'India'), ('USA', 'USA'), ('UK', 'UK'), ('Chinese', 'Chinese')], max_length=50)),
                ('zipcode', models.CharField(max_length=10)),
                ('payment_type', models.CharField(choices=[('Prepaid', 'Prepaid'), ('Postpaid', 'Postpaid')], max_length=20)),
                ('payment_term', models.CharField(choices=[('15 Days', '15 Days'), ('30 Days', '30 Days'), ('45 Days', '45 Days')], max_length=20)),
                ('billing_currency', models.CharField(choices=[('INR', 'INR'), ('USD', 'USD')], max_length=10)),
                ('gst_no', models.CharField(blank=True, max_length=20, null=True)),
                ('cin_no', models.CharField(blank=True, max_length=30, null=True)),
                ('is_domestic', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('wallet_available_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_credited_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_debited_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('topup_wallet_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
