# Generated by Django 5.2.13 on 2026-04-22 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='topup_wallet_amount',
        ),
        migrations.RemoveField(
            model_name='client',
            name='total_credited_amount',
        ),
        migrations.RemoveField(
            model_name='client',
            name='total_debited_amount',
        ),
        migrations.RemoveField(
            model_name='client',
            name='wallet_available_amount',
        ),
    ]
