# Generated by Django 5.2.13 on 2026-04-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_signin_client_company_address_line1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('client_campaign_id', models.CharField(blank=True, max_length=50, null=True)),
                ('reporting_id', models.CharField(blank=True, max_length=20, null=True)),
                ('purchase_order_id', models.CharField(blank=True, max_length=50, null=True)),
                ('campaign_name', models.CharField(max_length=255)),
                ('client_name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('subagency', models.CharField(blank=True, max_length=255, null=True)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Live', 'Live'), ('Paused', 'Paused'), ('Completed', 'Completed'), ('Active', 'Active')], default='Draft', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
